  spring:
    cloud:
      gateway:
        routes:
          - id: livre-service
            uri: http://localhost:8081/
            predicates:
              - Path=/livres/**
          - id: user-service
            uri: http://localhost:8082/
            predicates:
              - Path=/utilisateurs/**
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG
      org.springframework: DEBUG
      reactor.netty: DEBUG

